pieshop/pieshop-master/PieShop/Controllers/CakeController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using PieShop.Models;
using PieShop.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace PieShop.Controllers
{
    public class CakeController : Controller
    {
        private readonly ICakeRepository _CakeRepository;
        private readonly ICategoryRepository _categoryRepository;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public CakeController(ICakeRepository CakeRepository, ICategoryRepository categoryRepository, IWebHostEnvironment webHostEnvironment)
        {
            _CakeRepository = CakeRepository;
            _categoryRepository = categoryRepository;
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            DesertViewModel CakeViewModel = new DesertViewModel
            {
                Cakes = _CakeRepository.AllCakes
            };
            return View(CakeViewModel);
        }
        [Authorize]
        public ViewResult AddCake()
        {
            DesertViewModel CakeViewModel = new DesertViewModel
            {
                Categories = _categoryRepository.Categories
            };
            return View(CakeViewModel);
        }

        [Authorize]
        [HttpPost]
        public RedirectToActionResult AddCake(Cake cake)
        {
            if (cake == null)
                return RedirectToAction("AddCake");
            else
            {
                if (ModelState.IsValid)
                {
                    string uniqueFileName = UploadedFile(cake);
                    cake.CakePhoto = uniqueFileName;
                    _CakeRepository.CreateCake(cake);
                }
            }
            return RedirectToAction("Index");
        }
        [Authorize]
        private string UploadedFile(Cake model )
        {
            string uniqueFileName = null;

            if (model.CakePhotoName != null)
            {
                string uploadsFolder = Path.Combine(_webHostEnvironment.WebRootPath, "images");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + model.CakePhotoName.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    model.CakePhotoName.CopyTo(fileStream);
                }
            }
           
            return uniqueFileName;
        }
        [Authorize]
        public RedirectToActionResult RemoveCake(Guid id)
        {
            var cake = _CakeRepository.GetCakeById(id);
            _CakeRepository.RemoveCake(cake);
            return RedirectToAction("Index");
        }

        [Authorize]
        public ViewResult EditCake(Guid id)
        {
            var cake = _CakeRepository.GetCakeById(id);
            DesertViewModel CakeViewModel = new DesertViewModel
            {
                Cake = cake,
                Categories = _categoryRepository.Categories
            };
            return View(CakeViewModel);
        }

        [Authorize]
        [HttpPost]
        public RedirectToActionResult EditCake(Cake cake)
        {
            if (ModelState.IsValid)
            {
                string uniqueFileName = UploadedFile(cake);
                if (uniqueFileName != null) // if the user didn't change the photo, we won't assign a null to the photo name, we instead sent the photo name as hidden parameter, if a value is sent , the value would replace the hidden parameter
                    cake.CakePhoto = uniqueFileName;

                var the_cake = _CakeRepository.GetCakeById(cake.CakeId);
                if (the_cake != null)
                    _CakeRepository.EditCake(the_cake, cake);
            }
            return RedirectToAction("Index");
        }
        public IActionResult MakeCakeOfTheWeek(Guid id)
        {
            var cake = _CakeRepository.GetCakeById(id);
            _CakeRepository.MakeCakeOfTheWeek(cake);
            return RedirectToAction("Index");
        }
        public IActionResult Details(Guid id)
        {
            var cake = _CakeRepository.GetCakeById(id);
            if (cake == null)
                return NotFound();

            return View(cake);
        }
    }
}

pieshop/pieshop-master/PieShop/Controllers/PieController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using PieShop.Models;
using PieShop.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace PieShop.Controllers
{
    public class PieController : Controller
    {
        private readonly IPieRepository _pieRepository;
        private readonly ICategoryRepository _categoryRepository;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public PieController(IPieRepository pieRepository, ICategoryRepository categoryRepository, IWebHostEnvironment webHostEnvironment)
        {
            _pieRepository = pieRepository;
            _categoryRepository = categoryRepository;
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            DesertViewModel pieViewModel = new DesertViewModel
            {
                Pies = _pieRepository.AllPies
            };
            return View(pieViewModel);
        }
        [Authorize]
        public ViewResult AddPie()
        {
            DesertViewModel pieViewModel = new DesertViewModel
            {
                Categories = _categoryRepository.Categories              
            };
            return View(pieViewModel);
        }

        [Authorize]
        [HttpPost]
        public RedirectToActionResult AddPie(Pie pie)
        {
            if (pie == null)
                return RedirectToAction("AddPie");
            else
            {
                if(ModelState.IsValid)
                {
                    string uniqueFileName = UploadedFile(pie);
                    pie.PiePhoto = uniqueFileName;
                    _pieRepository.CreatePie(pie);
                }
            }
            return RedirectToAction("Index");
        }
        [Authorize]
        private string UploadedFile(Pie model)
        {
            string uniqueFileName = null;

            if (model.PiePhotoName != null)
            {
                string uploadsFolder = Path.Combine(_webHostEnvironment.WebRootPath, "images");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + model.PiePhotoName.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    model.PiePhotoName.CopyTo(fileStream);
                }
            }
            return uniqueFileName;
        }
        [Authorize]
        public RedirectToActionResult RemovePie(Guid id)
        {
             var pie =  _pieRepository.GetPieById(id);
             _pieRepository.RemovePie(pie);
            return RedirectToAction("Index");
        }

        [Authorize]
        public ViewResult EditPie(Guid id)
        {
            var pie = _pieRepository.GetPieById(id);
            DesertViewModel pieViewModel = new DesertViewModel
            {
                Pie = pie,
                Categories = _categoryRepository.Categories
            };
            return View(pieViewModel);
        }

        [Authorize]
        [HttpPost]
        public RedirectToActionResult EditPie(Pie pie)
        {
            if (ModelState.IsValid)
            {
                string uniqueFileName = UploadedFile(pie);
                if(uniqueFileName != null) // if the user didn't change the photo, we won't assign a null to the photo name, we instead sent the photo name as hidden parameter, if a value is sent , the value would replace the hidden parameter
                    pie.PiePhoto = uniqueFileName;
               
                var the_pie = _pieRepository.GetPieById(pie.PieId);
                if (the_pie != null)
                    _pieRepository.EditPie(the_pie, pie);
            }
            return RedirectToAction("Index");
        }
        public IActionResult MakePieOfTheWeek(Guid id)
        {
            var pie = _pieRepository.GetPieById(id);
            _pieRepository.MakePieOfTheWeek(pie);
            return RedirectToAction("Index");
        }
        public IActionResult Details(Guid id)
        {
            var pie = _pieRepository.GetPieById(id);
            if (pie == null)
                return NotFound();

            return View(pie);
        }
    }
}

pieshop/pieshop-master/PieShop/Views/Shared/_CakeCard.cshtml
@model Cake
<div class="col-sm-4 col-lg-4 col-md-4">
    <div class="thumbnail">
        <img src="images/@Model.CakePhoto" style="width:100%;height:150px;" alt="">
        <div class="caption">
            <h3 class="pull-right">@Model.Price.ToString("c")</h3>
            <h3>
                <a asp-controller="Cake"
                   asp-action="Details"
                   asp-route-id="@Model.CakeId">@Model.CakeName</a>
            </h3>
            <p>@Model.ShortDescreption</p>
        </div>
        <div class="addToCart">
            <p class="button" style="display:inline-block">
                <a class="btn btn-primary"
                   asp-controller="ShoppingCart"
                   asp-action="AddToCart"
                   asp-route-id="@Model.CakeId">Add to cart</a>
            </p>

            <p class="button" style="display:inline-block">
                <a class="btn btn-danger"
                   asp-controller="Cake"
                   asp-action="RemoveCake"
                   asp-route-id="@Model.CakeId">Remove</a>
            </p>

            <p class="button" style="display:inline-block">
                <a class="btn btn-secondary"
                   asp-controller="Cake"
                   asp-action="EditCake"
                   asp-route-id="@Model.CakeId">Edit</a>
            </p>
        </div>
    </div>
</div>

pieshop/pieshop-master/PieShop/Views/Shared/_Carousel.cshtml
<div class="row carousel-holder">
    <div class="col-md-12">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="item active">
                    <img class="slide-image" src="~/Images/carousel1.jpg" alt="">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/Images/carousel2.jpg" alt="">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/Images/carousel3.jpg" alt="">
                </div>
            </div>
            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
        </div>
    </div>
</div>

pieshop/pieshop-master/PieShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro">
    <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>
    <link href="~/Content/site.css" rel="stylesheet" />
</head>
<body>
    <div class="container">

        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                        <li><a asp-controller="Pie" asp-action="Index">Pies</a></li>
                        <li><a asp-controller="Cake" asp-action="Index">Cakes</a></li>
                        <li><a asp-controller="Pie" asp-action="AddPie">Add Pie</a></li>
                        <li><a asp-controller="Cake" asp-action="AddCake">Add Cake</a></li>
                        <li><a asp-controller="Category" asp-action="Index">Categories</a></li>
                        <li><a asp-controller="Category" asp-action="AddCategory">Add Category</a></li>
                        <partial name="_LoginPartial" />
                    </ul>
                </div>
            </div>
        </nav>

        <div class="row">
            <div class="col-md-3">
                <p class="lead">
                    <img class="img-responsive" alt="Bethany's Pie Shop'" src="~/Images/bethanylogo.png" />
                </p>
            </div>
            <div class="col-md-9">
                @RenderBody()
            </div>
        </div>
        @RenderSection("Scripts", required: false)
    </div>
</body>
</html>

pieshop/pieshop-master/PieShop/Views/Shared/_PieCard.cshtml
@model Pie
<div class="col-sm-4 col-lg-4 col-md-4">
    <div class="thumbnail">
        <img src="images/@Model.PiePhoto" style="width:100%;height:150px;" alt="">
        <div class="caption">
            <h3 class="pull-right">@Model.Price.ToString("c")</h3>
            <h3>
                <a asp-controller="Pie"
                   asp-action="Details"
                   asp-route-id="@Model.PieId">@Model.PieName</a>
            </h3>
            <p>@Model.ShortDescreption</p>
        </div>
        <div class="addToCart">
            <p class="button" style="display:inline-block">
                <a class="btn btn-primary"
                   asp-controller="ShoppingCart"
                   asp-action="AddToCart"
                   asp-route-id="@Model.PieId">Add to cart</a>
            </p>

            <p class="button" style="display:inline-block">
                <a class="btn btn-danger"
                   asp-controller="Pie"
                   asp-action="RemovePie"
                   asp-route-id="@Model.PieId">Remove</a>
            </p>

            <p class="button" style="display:inline-block">
                <a class="btn btn-secondary"
                   asp-controller="Pie"
                   asp-action="EditPie"
                   asp-route-id="@Model.PieId">Edit</a>
            </p>
        </div>
    </div>
</div>